import { describe, it, expect, mock, beforeEach } from 'bun:test'

// ─── Mocks (must be declared before the module is imported) ──────────────────

const mockGenerateText = mock()
mock.module('ai', () => ({ generateText: mockGenerateText }))
mock.module('@ai-sdk/openai', () => ({ openai: mock().mockReturnValue('fake-model') }))

const { polishReply, summarizeTicket, autoResolveTicket, classifyTicket } = await import('./ai.js')

// ─────────────────────────────────────────────────────────────────────────────

beforeEach(() => { mockGenerateText.mockReset() })

// ─── polishReply ──────────────────────────────────────────────────────────────

describe('polishReply', () => {
  it('returns the text generated by the AI model', async () => {
    mockGenerateText.mockResolvedValue({ text: 'Dear Jane, thank you for reaching out.' })
    const result = await polishReply('my draft', 'Jane')
    expect(result).toBe('Dear Jane, thank you for reaching out.')
  })

  it('passes the customer first name and draft body in the prompt', async () => {
    mockGenerateText.mockResolvedValue({ text: 'polished' })
    await polishReply('draft body text', 'Alice')
    const prompt: string = mockGenerateText.mock.calls[0][0].prompt
    expect(prompt).toContain('Alice')
    expect(prompt).toContain('draft body text')
  })
})

// ─── summarizeTicket ──────────────────────────────────────────────────────────

describe('summarizeTicket', () => {
  it('returns the AI-generated summary string', async () => {
    mockGenerateText.mockResolvedValue({ text: '• Customer cannot log in\n• Pending investigation' })
    const messages = [
      { senderType: 'customer', fromName: 'Bob', body: 'I cannot log in.' },
      { senderType: 'agent', fromName: 'Support', body: 'We are looking into this.' },
    ]
    const result = await summarizeTicket('Login broken', messages)
    expect(result).toContain('log in')
  })

  it('prefixes messages as [Customer] / [Agent] in the prompt', async () => {
    mockGenerateText.mockResolvedValue({ text: 'summary' })
    await summarizeTicket('Late order', [
      { senderType: 'customer', fromName: 'Jane', body: 'My order is late.' },
      { senderType: 'agent', fromName: 'Tom', body: 'We will check.' },
    ])
    const prompt: string = mockGenerateText.mock.calls[0][0].prompt
    expect(prompt).toContain('[Customer – Jane]')
    expect(prompt).toContain('[Agent – Tom]')
  })
})

// ─── autoResolveTicket ────────────────────────────────────────────────────────

describe('autoResolveTicket', () => {
  it('returns { canResolve: true, reply } when the AI responds positively', async () => {
    mockGenerateText.mockResolvedValue({ text: '{"canResolve":true,"reply":"Your refund is approved."}' })
    const result = await autoResolveTicket('Refund request', 'I want a refund.', 'KB content', 'Alice')
    expect(result).toEqual({ canResolve: true, reply: 'Your refund is approved.' })
  })

  it('returns { canResolve: false } when the AI responds negatively', async () => {
    mockGenerateText.mockResolvedValue({ text: '{"canResolve":false}' })
    const result = await autoResolveTicket('Legal threat', 'I will sue.', 'KB content', 'Bob')
    expect(result).toEqual({ canResolve: false })
  })

  it('returns { canResolve: false } when the AI response is not valid JSON', async () => {
    mockGenerateText.mockResolvedValue({ text: 'I cannot help with this.' })
    expect(await autoResolveTicket('subject', 'body', 'kb', 'Name')).toEqual({ canResolve: false })
  })

  it('returns { canResolve: false } when canResolve is true but reply is an empty string', async () => {
    mockGenerateText.mockResolvedValue({ text: '{"canResolve":true,"reply":""}' })
    expect(await autoResolveTicket('subject', 'body', 'kb', 'Name')).toEqual({ canResolve: false })
  })

  it('truncates the body to 3000 chars in the prompt', async () => {
    mockGenerateText.mockResolvedValue({ text: '{"canResolve":false}' })
    await autoResolveTicket('subject', 'x'.repeat(5_000), 'kb', 'Name')
    const prompt: string = mockGenerateText.mock.calls[0][0].prompt
    const xBlock = 'x'.repeat(3_000)
    expect(prompt).toContain(xBlock)
    expect(prompt).not.toContain('x'.repeat(3_001))
  })
})

// ─── classifyTicket ───────────────────────────────────────────────────────────

describe('classifyTicket', () => {
  it('returns "technical" for a technical AI response', async () => {
    mockGenerateText.mockResolvedValue({ text: 'technical' })
    expect(await classifyTicket('App crash', 'The app crashes on startup')).toBe('technical')
  })

  it('returns "refund" for a refund AI response', async () => {
    mockGenerateText.mockResolvedValue({ text: 'refund' })
    expect(await classifyTicket('Billing dispute', 'I was billed twice')).toBe('refund')
  })

  it('returns "general" for a general AI response', async () => {
    mockGenerateText.mockResolvedValue({ text: 'general' })
    expect(await classifyTicket('How-to', 'How do I reset my password?')).toBe('general')
  })

  it('returns null when the AI response is not a recognised category', async () => {
    mockGenerateText.mockResolvedValue({ text: 'unknown-category' })
    expect(await classifyTicket('subject', 'body')).toBeNull()
  })

  it('trims whitespace and lowercases the AI response before matching', async () => {
    mockGenerateText.mockResolvedValue({ text: '  Technical  ' })
    expect(await classifyTicket('subject', 'body')).toBe('technical')
  })
})
